apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  labels:
    app: converter
spec:
  replicas: {{ .Values.converter.replicas }}
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
#      securityContext:
#        runAsUser: 101
#        runAsGroup: 101
      volumes:
        - name: ds-files
          persistentVolumeClaim:
            claimName: ds-files
        - name: ds-license
          secret:
            secretName: license
        - name: bbuzg-ca
          secret:
            secretName: bbuzg-ca
        - name: configmap-default-json
          configMap:
            name: configmap-default-json
            items:
            - key: default.json
              path: default.json
      containers:
        - name: converter
          image: {{ .Values.converter.containerImage }}
          resources: {{- toYaml .Values.converter.resources | nindent 12 }}
          env:
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgresql-password
          - name: AMQP_PWD
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: rabbitmq-password
          - name: NODE_EXTRA_CA_CERTS
            value: '/usr/local/share/ca-certificates/bbuzg.crt'
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: '0'
          envFrom:
          - secretRef:
              name: jwt
          - configMapRef:
              name: documentserver
          volumeMounts:
          - name: ds-files
            mountPath: /var/lib/{{ .Values.product.name }}/documentserver/App_Data/cache/files
          - name: ds-license
            mountPath: /var/www/{{ .Values.product.name }}/Data
            readOnly: true
          - name: bbuzg-ca
            mountPath: /usr/local/share/ca-certificates
            readOnly: true
          - name: configmap-default-json
            mountPath: /etc/onlyoffice/documentserver/default.json
            subPath: default.json
